packages:
  - ".internal"
  - "bdd"
  - "chain"
  - "context-api"
  # deno-deploy excluded - deprecated Deno-only package
  - "event-emitter"
  - "fs"
  - "fx"
  - "jsonl-store"
  - "process"
  - "raf"
  - "signals"
  - "stream-helpers"
  - "task-buffer"
  - "test-adapter"
  - "timebox"
  - "tinyexec"
  - "watch"
  - "websocket"
  - "worker"
