packages:
  - "bdd"
  - "chain"
  - "context-api"
  - "deno-deploy"
  - "fx"
  - "jsonl-store"
  - "process"
  - "raf"
  - "signals"
  - "stream-helpers"
  - "task-buffer"
  - "test-adapter"
  - "timebox"
  - "tinyexec"
  - "watch"
  - "websocket"
  - "worker"
