/**
 * Build script for @effectionx/k6
 *
 * This script bundles:
 * 1. Conformance tests - for validating K6 runtime compatibility
 * 2. Main library - the @effectionx/k6 library with Effection bundled
 * 3. Demo scripts - example K6 scripts showing problem/solution pairs
 */

import * as esbuild from "esbuild";
import { mkdir, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";

// Ensure dist directory exists
await mkdir("dist", { recursive: true });
await mkdir("dist/demos", { recursive: true });

// Common esbuild options for K6 bundles
const k6BundleOptions = {
  bundle: true,
  format: "esm",
  target: "es2020",
  platform: "neutral", // K6's Sobek is not Node or browser
  sourcemap: true,
  minify: false, // Keep readable for debugging
  // K6 provides these modules - mark as external
  // Also mark node:* as external since Effection has dynamic imports for them
  // that only execute in Node environments
  external: ["k6", "k6/*", "node:*"],
};

// Bundle conformance tests for K6
await esbuild.build({
  ...k6BundleOptions,
  entryPoints: ["conformance/k6-runner.ts"],
  outfile: "dist/conformance-bundle.js",
  banner: {
    js: `/**
 * @effectionx/k6 Conformance Test Bundle
 * 
 * This file is auto-generated by build.js
 * Do not edit directly.
 * 
 * Run with: k6 run conformance-bundle.js
 */
`,
  },
});

console.log("Built: dist/conformance-bundle.js");

// Build the main library module
// This bundles Effection into the output so K6 scripts don't need external deps
await esbuild.build({
  ...k6BundleOptions,
  entryPoints: ["lib/mod.ts"],
  outfile: "dist/lib.js",
  banner: {
    js: `/**
 * @effectionx/k6 Library Bundle
 * 
 * Structured concurrency for K6 load testing.
 * Effection is bundled - no external dependencies needed.
 * 
 * Import in K6 scripts:
 *   import { vuIteration, group, http } from './lib.js';
 */
`,
  },
});

console.log("Built: dist/lib.js");

// Build demo scripts if they exist
const demosDir = "demos";
if (existsSync(demosDir)) {
  const demoFiles = (await readdir(demosDir)).filter((f) => f.endsWith(".ts"));

  for (const demoFile of demoFiles) {
    const outName = demoFile.replace(".ts", ".js");
    await esbuild.build({
      ...k6BundleOptions,
      entryPoints: [`${demosDir}/${demoFile}`],
      outfile: `dist/demos/${outName}`,
      banner: {
        js: `/**
 * @effectionx/k6 Demo: ${demoFile.replace(".ts", "")}
 * Auto-generated - do not edit directly.
 */
`,
      },
    });
    console.log(`Built: dist/demos/${outName}`);
  }
}

// Build the full package module (includes conformance exports)
await esbuild.build({
  ...k6BundleOptions,
  entryPoints: ["mod.ts"],
  outfile: "dist/mod.js",
});

console.log("Built: dist/mod.js");

console.log("\nBuild complete!");
